const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const root=path.resolve(__dirname,'../..');

function environment(){
  const c=vm.createContext({console,Date,JSON});
  for(const file of ['Chatbot.gs','Store.gs','Auth.gs','Logs.gs','AITools.gs','AIMemory.gs','AIProvider.gs','AIChatbot.gs','Code.gs'])vm.runInContext(fs.readFileSync(path.join(root,'apps-script',file),'utf8'),c,{filename:file});
  const db={};Object.keys(c.Schema).forEach(name=>db[name]=[]);
  const props={AUTH_SECRET:'test-secret',OWNER_EMAILS:'owner@example.test',AI_PROVIDER:'openai-compatible',AI_API_URL:'https://provider.example.test/chat',AI_API_KEY:'secret-key',AI_MODEL:'test-model'};
  c.setting_=key=>props[key]||'';c.rows_=name=>(db[name]||[]).map(row=>({...row}));c.append_=(name,row)=>(db[name]??=[]).push({...row});c.update_=()=>true;
  c.Utilities={getUuid:()=>crypto.randomUUID(),computeHmacSha256Signature:(v,k)=>crypto.createHmac('sha256',k).update(v).digest(),base64EncodeWebSafe:v=>Buffer.from(v).toString('base64url')};
  const cache=new Map();c.CacheService={getScriptCache:()=>({get:key=>cache.get(key)||null,put:(key,value)=>cache.set(key,value)})};c.LockService={getScriptLock:()=>({waitLock(){},releaseLock(){}})};c.rate_=()=>{};
  c.ContentService={MimeType:{JSON:'json'},createTextOutput:value=>({setMimeType:()=>JSON.parse(value)})};
  const branches=[{branch_id:'DU',branch_name:'U&I Mart Dubai',city:'Dubai',specialization:'Furniture & Kitchen Items',address:'Test address',opening_hours:'9–9',is_active:true},{branch_id:'AD',branch_name:'U&I Mart Abu Dhabi',city:'Abu Dhabi',specialization:'Electronics & Kitchen Items',is_active:true},{branch_id:'SH',branch_name:'U&I Mart Sharjah',city:'Sharjah',specialization:'Hardware, Pipes & Kitchen Items',is_active:true}];
  const products=[{product_id:'SOFA1',product_name:'Compact Sofa',category:'Furniture',branch:'Dubai',price:1800,quantity:3,brand:'U&I',keywords:'sofa apartment',description:'Compact seating',is_active:true},{product_id:'TV1',product_name:'Samsung 55 Inch TV',category:'Electronics',branch:'Abu Dhabi',price:1799,quantity:10,brand:'Samsung',keywords:'samsung tv television 55 inch',is_active:true},{product_id:'SOFA2',product_name:'Large Sofa',category:'Furniture',branch:'Dubai',price:3200,quantity:1,brand:'U&I',keywords:'sofa',is_active:true}];
  const deals=[{deal_id:'D1',title:'Dubai furniture saving',branch:'Dubai',category:'Furniture',description:'Current offer',is_active:true}];
  c.DataService.getBranches=()=>branches;c.DataService.getProducts=()=>products;c.DataService.getDeals=()=>deals;c.DataService.saveChatLog=row=>db.Chat_Logs.push({...row});
  c.UrlFetchApp={fetch:(url,options)=>({getResponseCode:()=>200,getContentText:()=>JSON.stringify({choices:[{message:{content:'I found matching information in the trusted U&I data.'}}]})})};
  const user={user_id:'U1',name:'Muhammad Ali',email:'customer@example.test',role:'customer',status:'active',password_hash:'hash',email_verified:true,auth_session:'AUTH1'};
  c.authenticate_=(token,required)=>token==='valid-token'?user:(required?(()=>{const error=new Error('Please sign in to continue.');error.code='AUTH_REQUIRED';throw error;})():null);
  const call=(token,message='I need a sofa around AED 2500',extra={})=>c.doPost({postData:{contents:JSON.stringify({action:'aiChat',session_id:'browser-session',token,message,conversation_id:'conversation-123',request_id:'request-'+crypto.randomUUID(),...extra})}});
  return{c,db,props,call,user};
}

test('AI route rejects logged-out and invalid sessions before retrieval/provider access',()=>{const {call}=environment();for(const token of ['', 'forged']){const result=call(token);assert.equal(result.success,false);assert.equal(result.code,'AUTH_REQUIRED');}});
test('budget search returns only trusted in-stock products within budget',()=>{const {c}=environment();const result=c.AITools.build('Furniture in Dubai under AED 2500',{messages:[],context:{}});assert.equal(result.intent,'budget');assert.deepEqual(Array.from(result.products,p=>p.product_id),['SOFA1']);assert.equal(result.products[0].price,1800);});
test('authenticated AI call uses trusted tools, memory, and identifiable logging',()=>{const {call,db}=environment();const result=call('valid-token');assert.equal(result.success,true);assert.equal(result.products.length,1);assert.equal(result.products[0].product_id,'SOFA1');assert.equal(db.Chat_Logs.length,1);assert.equal(db.Chat_Logs[0].chatbot_type,'ai_assistant');assert.equal(db.Chat_Logs[0].user_id,'U1');});
test('follow-up memory retains category and applies the new budget',()=>{const {c}=environment();const memory={messages:[],context:{category:'Furniture',branch:'Dubai',product_ids:['SOFA1','SOFA2']}};const result=c.AITools.build('Around AED 2000',memory);assert.equal(result.context.category,'Furniture');assert.equal(result.products[0].product_id,'SOFA1');assert.ok(result.products.every(p=>p.price<=2000));});
test('comparison uses only backend product fields',()=>{const {c}=environment();const result=c.AITools.build('Compare these two',{messages:[],context:{category:'Furniture',branch:'Dubai',product_ids:['SOFA1','SOFA2']}});assert.equal(result.intent,'comparison');assert.deepEqual(Array.from(result.products,p=>p.product_id),['SOFA1','SOFA2']);assert.equal(Object.hasOwn(result.products[0],'password_hash'),false);});
test('stock, deals, and branch guidance are retrieved from backend records',()=>{const {c}=environment();assert.equal(c.AITools.build('Is the sofa available?',{messages:[],context:{}}).products[0].quantity,3);assert.equal(c.AITools.build('What furniture deals are in Dubai?',{messages:[],context:{}}).deals[0].deal_id,'D1');assert.equal(c.AITools.build('Where is the Dubai branch?',{messages:[],context:{}}).branches[0].address,'Test address');});
test('an authenticated owner can use the same non-admin AI route',()=>{const env=environment();env.user.role='owner';const result=env.call('valid-token','Show furniture under AED 2500');assert.equal(result.success,true);assert.equal(result.products[0].product_id,'SOFA1');});
test('missing provider configuration does not fake a successful answer',()=>{const {call,props}=environment();delete props.AI_API_KEY;const result=call('valid-token');assert.equal(result.success,false);assert.equal(result.code,'AI_NOT_CONFIGURED');});
test('provider output with invented numeric facts is rejected',()=>{const {c,call}=environment();c.UrlFetchApp.fetch=()=>({getResponseCode:()=>200,getContentText:()=>JSON.stringify({choices:[{message:{content:'It costs AED 9999.'}}]})});const result=call('valid-token');assert.equal(result.success,false);assert.match(result.message,/unavailable/);});
test('explicit category and product queries replace stale Dubai furniture context',()=>{
  const {c}=environment();let memory={messages:[],context:{}};
  const furniture=c.AITools.build('I need furniture under AED 2500.',memory);assert.equal(furniture.filters.category,'Furniture');assert.equal(furniture.filters.branch,null);assert.deepEqual(Array.from(furniture.products,p=>p.product_id),['SOFA1']);memory.context=furniture.context;
  const deals=c.AITools.build('What deals are available in Dubai?',memory);assert.equal(deals.filters.branch,'Dubai');assert.equal(deals.deals[0].deal_id,'D1');memory.context=deals.context;
  const electronicsBranch=c.AITools.build('Which branch should I visit for electronics?',memory);assert.equal(electronicsBranch.filters.category,'Electronics');assert.equal(electronicsBranch.filters.branch,null);assert.deepEqual(Array.from(electronicsBranch.branches,b=>b.city),['Abu Dhabi']);memory.context=electronicsBranch.context;
  const tv=c.AITools.build('Is the Samsung 55 inch TV available?',memory);assert.equal(tv.filters.product,'Samsung 55 Inch TV');assert.equal(tv.filters.branch,null);assert.equal(tv.products[0].branch,'Abu Dhabi');assert.equal(tv.products[0].price,1799);assert.equal(tv.products[0].quantity,10);assert.equal(tv.products[0].stock_status,'in_stock');
  const afterDubai=c.AITools.build('Do you have electronics?',{messages:[],context:deals.context});assert.equal(afterDubai.filters.branch,null);assert.equal(afterDubai.branches[0].city,'Abu Dhabi');assert.equal(afterDubai.products[0].branch,'Abu Dhabi');
});
test('memory is retained only for genuine follow-ups and replaced by a new category',()=>{
  const {c}=environment();const sofa=c.AITools.build('I need a sofa.',{messages:[],context:{}});assert.equal(sofa.context.category,'Furniture');
  const budget=c.AITools.build('Under AED 2500.',{messages:[],context:sofa.context});assert.equal(budget.filters.category,'Furniture');assert.equal(budget.products[0].product_id,'SOFA1');
  const electronics=c.AITools.build('Now I need electronics.',{messages:[],context:budget.context});assert.equal(electronics.filters.category,'Electronics');assert.equal(electronics.filters.branch,null);assert.equal(electronics.filters.budget,null);assert.ok(electronics.products.every(p=>p.category==='Electronics'));
});
test('provider Markdown is converted to safe plain text',()=>{const {c,call}=environment();c.UrlFetchApp.fetch=()=>({getResponseCode:()=>200,getContentText:()=>JSON.stringify({choices:[{message:{content:'**Samsung 55 Inch TV** is in stock for AED 1799.'}}]})});const result=call('valid-token','Is the Samsung 55 inch TV available?');assert.equal(result.success,true);assert.equal(result.reply,'Samsung 55 Inch TV is in stock for AED 1799.');assert.doesNotMatch(result.reply,/\*\*/);});
test('one transient provider failure is retried without duplicate logging',()=>{const {c,call,db}=environment();let requests=0;c.UrlFetchApp.fetch=()=>{requests++;return requests===1?{getResponseCode:()=>503,getContentText:()=>''}:{getResponseCode:()=>200,getContentText:()=>JSON.stringify({choices:[{message:{content:'Trusted results are ready.'}}]})};};const result=call('valid-token');assert.equal(result.success,true);assert.equal(requests,2);assert.equal(db.Chat_Logs.length,1);});
test('permanent provider errors are not retried',()=>{const {c,call,db}=environment();let requests=0;c.UrlFetchApp.fetch=()=>{requests++;return{getResponseCode:()=>401,getContentText:()=>''};};const result=call('valid-token');assert.equal(result.success,false);assert.equal(requests,1);assert.equal(db.Chat_Logs.length,0);});
test('provider history is retained for a genuine follow-up but cleared for a new topic',()=>{const {c,call}=environment();const requests=[];c.UrlFetchApp.fetch=(url,options)=>{requests.push(JSON.parse(options.payload));return{getResponseCode:()=>200,getContentText:()=>JSON.stringify({choices:[{message:{content:'Trusted results are ready.'}}]})};};call('valid-token','I need a sofa.');call('valid-token','Under AED 2500.');call('valid-token','Now I need electronics.');assert.equal(requests[0].messages.length,2);assert.equal(requests[1].messages.length,4);assert.equal(requests[2].messages.length,2);assert.doesNotMatch(JSON.stringify(requests[2]),/sofa|Furniture|Dubai/i);});
