"""Keep the browser preview identical to the Apps Script intent engine."""
from pathlib import Path
root = Path(__file__).resolve().parents[1]
source = (root / 'apps-script/Chatbot.gs').read_text(encoding='utf-8')
(root / 'assets/js/chat-engine.js').write_text('// Generated by scripts/sync-engine.py. Edit apps-script/Chatbot.gs.\n' + source + '\nexport { ChatEngine };\n', encoding='utf-8')
